version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vocablearning-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Samsung@11
      MYSQL_DATABASE: vocablearning
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ollama:
    image: ollama/ollama:latest
    container_name: vocablearning-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ollama serve &
        sleep 5
        ollama pull llama3.2
        wait

  app:
    build: .
    container_name: vocablearning-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/vocablearning
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Samsung@11
      SPRING_AI_OLLAMA_BASE_URL: http://ollama:11434
    depends_on:
      mysql:
        condition: service_healthy
      ollama:
        condition: service_started

volumes:
  mysql-data:
  ollama-data:
